services:
  - type: web
    name: agent
    env: python
    plan: free
    region: frankfurt
    repo: https://github.com/xbeat/agent
    branch: main
    autoDeploy: true    
    buildCommand: pip install -r requirements.txt
    startCommand: python agent.py
    envVars:
      - key: ENV
        value: prod
      - key: DATABASE_URL
        sync: false  # URL del database Neon
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GOOGLE_API_KEY
        sync: false